### ISSUE TITLE
Teacher should be able to edit feedback and scores

### ISSUE THREAD

**Issue by GeorgeHahn** [jflexlanoue/CS490#29]

**Comment by garykc** [comment]
Fixed, but feedback is encapsulated in `["` and `"]` (e.g. [here](http://imagizer.imageshack.com/img922/6180/ICTZbn.png) so instructor will need to type the feedback inside the bracket/quote. That part needs to be fixed by middle/backend so that everything inside the feedback textbox is considered feedback rather than just everything inside the bracket/quote.

**Comment by GeorgeHahn** [comment]
You should be able to handle this on the front end by taking index [0] of the property you're displaying. If that doesn't work, json_decode it and take the 0 index of the result.

It would also be nice to replace the escaped <br>'s with actual line breaks. I think there's a built in twig filter to handle html in templates - you might check their docs for that. Otherwise, I wrote a twig filter that should help with this or serve as a template for another one. Check the util php file; it's the function that does a bunch of string replacing.

Great work,

Cheers

From: garykc

Sent: Saturday, August 6, 3:12 PM

Subject: Re: [jflexlanoue/CS490] Teacher should be able to edit feedback and scores (#29)

To: jflexlanoue/CS490

Cc: George Hahn, Author

Fixed, but feedback is encapsulated in [" and "] (e.g. here so instructor will need to type the feedback inside the bracket/quote. That part needs to be fixed by middle/backend so that everything inside the feedback textbox is considered feedback rather than just everything inside the bracket/quote.
