### ISSUE TITLE
Adding new question bug

### ISSUE THREAD

**Issue by garykc** [jflexlanoue/CS490#54]

**Comment by GeorgeHahn** [comment]
This is due to 6bc2cc3a6c6481a302b954b2f5a25bf0197f0815. All questions now require a **points** field, which will be the default point value of that question when added to an exam. Furthermore, exams must be able to override this point value with a custom value. This behavior is implemented in 64b417f3ead3dd4d763db3314e1936e386427361. Both are shown in the [docs](https://github.com/jflexlanoue/CS490/wiki/Backend-API).

**Comment by GeorgeHahn** [comment]
Fixed this. There were some other fields that shouldn't have been required. Sorry about that.
